name: Upload Python Package

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Publish package
      uses: JRubics/poetry-publish@v1.17
      with:
        repository_name: testpypi
        ignore_dev_requirements: true
        repository_url: https://test.pypi.org/legacy/
        pypi_token: ${{ secrets.PYPI_API_TOKEN }}
